### ISSUE TITLE
Chimera Chain English Spec

### ISSUE THREAD

**Issue by isheff** [anoma/typhon#48]
Properly describe chimera chains within the [typhon english language spec](https://specs.anoma.net/main/components/typhon.html). This means putting together consensus in multiple rounds, and connecting mempool, consensus, and execution layers. 

## Prerequisites
- [ ] https://github.com/anoma/typhon/issues/41
- [ ] https://github.com/anoma/specs/issues/123

## Sub-Tasks
- [ ] Proposer selection protocol for multi-decision Heterogeneous Paxos
- [ ] Chimera State machine
- [ ] protocol for moving resources between chimera chains / base chains
