### ISSUE TITLE
Chimera Chain Blog Post

### ISSUE THREAD

**Issue by isheff** [anoma/typhon#49]
Post to the Anoma blog a description of what we're trying to accomplish with Chimera Chains, and how those are supposed to work. 

## Prerequisite
- [ ] https://github.com/anoma/typhon/issues/48
    - although perhaps this doesn't really have to be completed for the blog post to work
 
## Sub-Tasks
- [ ] establish outline
- [ ] construct helpful diagrams
- [ ] fill in explanatory text
- [ ] internal review
- [ ] publish
