### ISSUE TITLE
Execution Engine Stateright Prototype

### ISSUE THREAD

**Issue by isheff** [anoma/typhon#51]
Building on the [english spec](https://specs.anoma.net/main/components/typhon/execution.html), construct a prototype version of the Execution Engine in the [Stateright](https://github.com/stateright/stateright) framework. This may involve some kind of "dummy" Taiga API. Ideally, this would match up with the [formal spec](https://github.com/anoma/typhon/issues/50).

This will have to match up with the [Heterogeneous Paxos Stateright Prototype](https://github.com/anoma/typhon/issues/45) and the [Heterogeneous Narwhal Stateright Prototype](https://github.com/anoma/typhon/issues/44) to be useful. 

## Prerequisites
- [ ] https://github.com/anoma/specs/issues/123
- [ ] https://github.com/anoma/typhon/issues/45
- [ ] https://github.com/anoma/typhon/issues/44

## Sub-Tasks
- [ ] Shards
- [ ] Executors
- [ ] Full-Nodes?
- [ ] Garbage collection messages
