### ISSUE TITLE
Coherent Typhon Formal Spec

### ISSUE THREAD

**Issue by isheff** [anoma/typhon#53]
After each component has been formalized, combine the mempool, consensus, and execution engine formal specs into a larger formal spec (in [TLA+](https://lamport.azurewebsites.net/tla/tla.html) or similar) for which we can check end-to-end properties. Ideally, this would match the [english spec](https://github.com/anoma/typhon/issues/52).

## Prerequisites
- [ ] https://github.com/anoma/typhon/issues/42
- [ ] https://github.com/anoma/typhon/issues/50

## Sub-Tasks
- [ ] combine spec text together (may involve matching up different representations of stuff)
- [ ] prove end-to-end serializability: based on proven properties of consensus and mempool, the execution engine in fact is equivalent to a serial execution
- [ ] prove end-to-end censorship resistance
