### ISSUE TITLE
Multi-Round Heterogeneous Paxos

### ISSUE THREAD

**Issue by isheff** [anoma/typhon#54]
Extend Heterogeneous Paxos from making a single decision to making multiple decisions, necessary to decide on successive blocks. In its simplest form, this can just run the single-decision mode over and over, but we might want to think about what, if anything, we want to keep from previous rounds. TCP channels seem like a good thing to re-use, for example. 

## Prerequisites
- [ ] https://github.com/anoma/typhon/issues/34
- [ ] https://github.com/anoma/typhon/issues/45

## Sub-Tasks
- [ ] Choose a proposer strategy: how do we choose who proposes, and what time-outs do we use?
- [ ] [English Spec](https://specs.anoma.net/main/components/typhon/heterogeneous_paxos.html)
- [ ] [Formal Spec](https://github.com/heliaxdev/typhon/blob/master/tla/HPaxos.tla)
- [ ] [Prototype](https://github.com/anoma/typhon/issues/45)
